[project]
name = "visualizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "biopython>=1.85",
    "flask>=3.1.0",
    "flask-cors>=5.0.1",
    "gffutils>=0.13",
]
